version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - '9092:9092'
    env_file:
      - .env
    depends_on:
      - zookeeper
